from enum import Enum


class Phase(Enum):
    START = 0
    # PICK_ADVENTURER_POSITION
    # PICK_TEMPLE_POSITION
    SAMPLE_NEXT_TILE = 1
    SHOW_NEXT_TILE = 2
    MOVE_NEXT_TILE = 3
    SELECT_ADVENTURER_TO_MOVE = 4
    SELECT_ADVENTURER_DESTINATION = 5
    MOVE_ADVENTURER_TO_DESTINATION = 6
    UPDATE_SCORE = 7
    END = 8
